In [11]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory
import matplotlib.pyplot as plt
import seaborn as sns 
import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/car-data/CarPrice_Assignment.csv
/kaggle/input/car-data/Data Dictionary - carprices.xlsx

# Table of Content
* import dataset
* drop unnecessary columns
* transform categorical into numerical 
* train test split
* scaling 
* training by linear regression
* calculate accuracy

In [12]:
df=pd.read_csv('/kaggle/input/car-data/CarPrice_Assignment.csv')

In [13]:
df.head(10)

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.000
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.000
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.000
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.000
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.000
5,6,2,audi fox,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250.000
6,7,1,audi 100ls,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710.000
7,8,1,audi 5000,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920.000
8,9,1,audi 4000,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875.000
9,10,0,audi 5000s (diesel),gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,17859.167

In [14]:
df.shape

(205, 26)

In [15]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase',
       'carlength', 'carwidth', 'carheight', 'curbweight', 'enginetype',
       'cylindernumber', 'enginesize', 'fuelsystem', 'boreratio', 'stroke',
       'compressionratio', 'horsepower', 'peakrpm', 'citympg', 'highwaympg',
       'price'],
      dtype='object')

# dropping unnecessary columns

In [16]:
df=df.drop(columns=['car_ID','symboling','CarName'])

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fueltype          205 non-null    object
 1   aspiration        205 non-null    object
 2   doornumber        205 non-null    object
 3   carbody           205 non-null    object
 4   drivewheel        205 non-null    object
 5   enginelocation    205 non-null    object
 6   wheelbase         205 non-null    float64
 7   carlength         205 non-null    float64
 8   carwidth          205 non-null    float64
 9   carheight         205 non-null    float64
 10  curbweight        205 non-null    int64
 11  enginetype        205 non-null    object
 12  cylindernumber    205 non-null    object
 13  enginesize        205 non-null    int64
 14  fuelsystem        205 non-null    object
 15  boreratio         205 non-null    float64
 16  stroke            205 non-null    float64
 17  compressionratio  205 non-null    float64
 18  horsepower        205 non-null    int64
 19  peakrpm           205 non-null    int64
 20  citympg           205 non-null    int64
 21  highwaympg        205 non-null    int64
 22  price             205 non-null    float64
dtypes: float64(8), int64(6), object(9)
memory usage: 37.0+ KB

In [18]:
df['boreratio'] = df['boreratio'].astype(int)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 23 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fueltype          205 non-null    object
 1   aspiration        205 non-null    object
 2   doornumber        205 non-null    object
 3   carbody           205 non-null    object
 4   drivewheel        205 non-null    object
 5   enginelocation    205 non-null    object
 6   wheelbase         205 non-null    float64
 7   carlength         205 non-null    float64
 8   carwidth          205 non-null    float64
 9   carheight         205 non-null    float64
 10  curbweight        205 non-null    int64
 11  enginetype        205 non-null    object
 12  cylindernumber    205 non-null    object
 13  enginesize        205 non-null    int64
 14  fuelsystem        205 non-null    object
 15  boreratio         205 non-null    int64
 16  stroke            205 non-null    float64
 17  compressionratio  205 non-null    float64
 18  horsepower        205 non-null    int64
 19  peakrpm           205 non-null    int64
 20  citympg           205 non-null    int64
 21  highwaympg        205 non-null    int64
 22  price             205 non-null    float64
dtypes: float64(7), int64(7), object(9)
memory usage: 37.0+ KB

# converting float to int

In [20]:
df['stroke'] = df['stroke'].astype(int)
df['compressionratio'] = df['compressionratio'].astype(int)
df['price'] = df['price'].astype(int)
df['wheelbase'] = df['wheelbase'].astype(int)
df['carlength'] = df['carlength'].astype(int)
df['carwidth'] = df['carwidth'].astype(int)
df['carheight'] = df['carheight'].astype(int)

In [23]:
df.fuelsystem.value_counts()

mpfi    94
2bbl    66
idi     20
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64

In [24]:
df.isnull().sum()

fueltype            0
aspiration          0
doornumber          0
carbody             0
drivewheel          0
enginelocation      0
wheelbase           0
carlength           0
carwidth            0
carheight           0
curbweight          0
enginetype          0
cylindernumber      0
enginesize          0
fuelsystem          0
boreratio           0
stroke              0
compressionratio    0
horsepower          0
peakrpm             0
citympg             0
highwaympg          0
price               0
dtype: int64

In [25]:
df=df.drop(columns=['fuelsystem'])

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   fueltype          205 non-null    object
 1   aspiration        205 non-null    object
 2   doornumber        205 non-null    object
 3   carbody           205 non-null    object
 4   drivewheel        205 non-null    object
 5   enginelocation    205 non-null    object
 6   wheelbase         205 non-null    int64
 7   carlength         205 non-null    int64
 8   carwidth          205 non-null    int64
 9   carheight         205 non-null    int64
 10  curbweight        205 non-null    int64
 11  enginetype        205 non-null    object
 12  cylindernumber    205 non-null    object
 13  enginesize        205 non-null    int64
 14  boreratio         205 non-null    int64
 15  stroke            205 non-null    int64
 16  compressionratio  205 non-null    int64
 17  horsepower        205 non-null    int64
 18  peakrpm           205 non-null    int64
 19  citympg           205 non-null    int64
 20  highwaympg        205 non-null    int64
 21  price             205 non-null    int64
dtypes: int64(14), object(8)
memory usage: 35.4+ KB

In [27]:
df.enginetype.value_counts()

ohc      148
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: enginetype, dtype: int64

In [28]:
df=df.drop(columns=['enginetype'])

In [29]:
df.cylindernumber.value_counts()

four      159
six        24
five       11
eight       5
two         4
three       1
twelve      1
Name: cylindernumber, dtype: int64

In [30]:
df=df.drop(columns=['cylindernumber'])

In [31]:
df.enginelocation.value_counts()

front    202
rear       3
Name: enginelocation, dtype: int64

In [33]:
for i in range(0,205):
    if df['enginelocation'][i]=="front":
        df['enginelocation'][i]=1
    else:
        df['enginelocation'][i]=0

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [34]:
df.head(10)

,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,gas,std,two,convertible,rwd,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27,13495
1,gas,std,two,convertible,rwd,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27,16500
2,gas,std,two,hatchback,rwd,0,94,171,65,52,2823,152,2,3,9,154,5000,19,26,16500
3,gas,std,four,sedan,fwd,0,99,176,66,54,2337,109,3,3,10,102,5500,24,30,13950
4,gas,std,four,sedan,4wd,0,99,176,66,54,2824,136,3,3,8,115,5500,18,22,17450
5,gas,std,two,sedan,fwd,0,99,177,66,53,2507,136,3,3,8,110,5500,19,25,15250
6,gas,std,four,sedan,fwd,0,105,192,71,55,2844,136,3,3,8,110,5500,19,25,17710
7,gas,std,four,wagon,fwd,0,105,192,71,55,2954,136,3,3,8,110,5500,19,25,18920
8,gas,turbo,four,sedan,fwd,0,105,192,71,55,3086,131,3,3,8,140,5500,17,20,23875
9,gas,turbo,two,hatchback,4wd,0,99,178,67,52,3053,131,3,3,7,160,5500,16,22,17859

In [35]:
df.drivewheel.value_counts()

fwd    120
rwd     76
4wd      9
Name: drivewheel, dtype: int64

# transforming categorical to numerical

In [48]:
for i in range(0,205):
    if df['drivewheel'][i]=="fwd":
        df['drivewheel'][i]=1
    elif (df['drivewheel']=="4wd").any():
        df['drivewheel'][i]=0
    else:
        df['drivewheel'][i]=2

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  import sys

In [49]:
df['drivewheel'].nunique

<bound method IndexOpsMixin.nunique of 0      0
1      0
2      0
3      1
4      0
      ..
200    2
201    2
202    2
203    2
204    2
Name: drivewheel, Length: 205, dtype: object>

In [50]:
df=df.drop(columns=['carbody','aspiration'])

In [51]:
df.doornumber.value_counts()

four    115
two      90
Name: doornumber, dtype: int64

In [52]:
for i in range(0,205):
    if df['doornumber'][i]=="four":
        df['doornumber'][i]=1
    else:
        df['doornumber'][i]=0

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until

In [53]:
df['doornumber']

0      0
1      0
2      0
3      1
4      1
      ..
200    1
201    1
202    1
203    1
204    1
Name: doornumber, Length: 205, dtype: object

In [54]:
df.fueltype.value_counts()

gas       185
diesel     20
Name: fueltype, dtype: int64

In [55]:
for i in range(0,205):
    if df['fueltype'][i]=="gas":
        df['fueltype'][i]=1
    else:
        df['fueltype'][i]=0

/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/opt/conda/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

In [56]:
df['fueltype']

0      1
1      1
2      1
3      1
4      1
      ..
200    1
201    1
202    1
203    0
204    1
Name: fueltype, Length: 205, dtype: object

In [57]:
df.head(10)

,fueltype,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,0,0,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27,13495
1,1,0,0,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27,16500
2,1,0,0,0,94,171,65,52,2823,152,2,3,9,154,5000,19,26,16500
3,1,1,1,1,99,176,66,54,2337,109,3,3,10,102,5500,24,30,13950
4,1,1,0,0,99,176,66,54,2824,136,3,3,8,115,5500,18,22,17450
5,1,0,1,1,99,177,66,53,2507,136,3,3,8,110,5500,19,25,15250
6,1,1,1,1,105,192,71,55,2844,136,3,3,8,110,5500,19,25,17710
7,1,1,1,1,105,192,71,55,2954,136,3,3,8,110,5500,19,25,18920
8,1,1,1,1,105,192,71,55,3086,131,3,3,8,140,5500,17,20,23875
9,1,0,0,0,99,178,67,52,3053,131,3,3,7,160,5500,16,22,17859

In [58]:
x=df.iloc[:,0:-1]

In [59]:
x

,fueltype,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
0,1,0,0,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27
1,1,0,0,0,88,168,64,48,2548,130,3,2,9,111,5000,21,27
2,1,0,0,0,94,171,65,52,2823,152,2,3,9,154,5000,19,26
3,1,1,1,1,99,176,66,54,2337,109,3,3,10,102,5500,24,30
4,1,1,0,0,99,176,66,54,2824,136,3,3,8,115,5500,18,22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,1,1,2,0,109,188,68,55,2952,141,3,3,9,114,5400,23,28
201,1,1,2,0,109,188,68,55,3049,141,3,3,8,160,5300,19,25
202,1,1,2,0,109,188,68,55,3012,173,3,2,8,134,5500,18,23
203,0,1,2,0,109,188,68,55,3217,145,3,3,23,106,4800,26,27
204,1,1,2,0,109,188,68,55,3062,141,3,3,9,114,5400,19,25

In [60]:
y=df.iloc[:,-1]

In [61]:
y

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: int64

In [63]:
from sklearn.model_selection import train_test_split

# train test split

In [64]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [75]:
x_test

,fueltype,doornumber,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,curbweight,enginesize,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg
15,1,1,0,0,103,189,66,55,3230,209,3,3,8,182,5400,16,22
9,1,0,0,0,99,178,67,52,3053,131,3,3,7,160,5500,16,22
100,1,1,1,1,97,173,65,54,2302,120,3,3,8,97,5200,27,34
132,1,0,1,1,99,186,66,56,2658,121,3,3,9,110,5250,21,28
68,0,1,0,0,110,190,70,58,3750,183,3,3,21,123,4350,22,25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,1,0,0,0,95,169,65,49,2380,70,3,3,9,101,6000,17,23
128,1,0,0,0,89,168,65,51,2800,194,3,2,9,207,5900,17,25
76,1,0,1,1,93,157,64,50,1918,92,2,3,9,68,5500,37,41
144,1,1,0,0,97,172,65,54,2385,108,3,2,9,82,4800,24,25
104,1,0,0,0,91,170,67,49,3071,181,3,3,9,160,5200,19,25

In [65]:
from sklearn.preprocessing import StandardScaler

# scaling

In [66]:
scaler=StandardScaler()

In [67]:
x_train_scaled=scaler.fit_transform(x_train)

In [79]:
x_test_scaled=scaler.fit_transform(x_test)

In [80]:
x_test_scaled

array([[ 0.38490018,  0.87831007, -1.34913081, ...,  0.76952735,
        -1.31581608, -1.20210967],
       [ 0.38490018, -1.13855009, -1.34913081, ...,  0.99404827,
        -1.31581608, -1.20210967],
       [ 0.38490018,  0.87831007,  0.290989  , ...,  0.32048551,
         0.11087163,  0.27863469],
       ...,
       [ 0.38490018, -1.13855009,  0.290989  , ...,  0.99404827,
         1.40786045,  1.14240223],
       [ 0.38490018,  0.87831007, -1.34913081, ..., -0.57759818,
        -0.27822502, -0.83192358],
       [ 0.38490018, -1.13855009, -1.34913081, ...,  0.32048551,
        -0.92671943, -0.83192358]])

# linear regression because data has linear behaviour

In [69]:
from sklearn.linear_model import LinearRegression

In [70]:
lr=LinearRegression()

In [71]:
lr.fit(x_train_scaled,y_train)

LinearRegression()

In [81]:
y_pred=lr.predict(x_test_scaled)

In [85]:
from sklearn.metrics import r2_score

In [87]:
r2_score(y_test,y_pred)

0.8455897378219857

# got 84.5 % accuracy